baseurl: "/"
permalink: pretty
title: "Tributary"
collections_dir: collections
markdown: kramdown
highlighter: rouge

sass:
  indentWidth: 4
  style: compact
  precision: 10

google_analytics_id: UA-221887922-1

logo: assets/images/logo/logo.svg

aqlogo:
  logo_desktop_image: assets/images/logo/logo.svg
  logo_desktop_text: <strong></strong>
  logo_mobile_image: assets/images/logo/logo-mobile.svg
  logo_mobile_text: ""
  logo_desktop_height: "80px"
  logo_desktop_width: "80px"
  logo_mobile_height: "36px"
  logo_mobile_width: "36px"

seo:
  meta_twitter_site: "@neoslashnet"
  meta_twitter_creator: "@neoslashnet"
  meta_og_image: "assets/images/logo/logo.svg"

social:
  name: Aquia
  links:
    - https://linkedin.com/company/aquia-llc
    - https://github.com/aquia-inc

plugins:
  - jekyll-environment-variables
  - jekyll-postcss
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

paginate: 3
paginate_path: /blog/page:num/

collections:
  posts:
    output: true
    permalink: /blog/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "categories"
    values:
      layout: category
      permalink: /category/:basename/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package.json
  - package-lock.json
  - vendor
  - LICENSE.md
  - LICENSE
  - README.md
  - .vscode
  - .gitignore
  - .liquidrc
  - postcss.config.js
  - tailwind.config.js
  - netlify.toml
